<a href="https://colab.research.google.com/github/GimenesPaula/GimenesPaula/blob/main/Lan%C3%A7amentos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fazer Upload planilhas
1.   Launches
2.   Inci

In [18]:
#Launches
from google.colab import files
uploaded = files.upload()

Saving Brasil, 30-09-25.xlsx to Brasil, 30-09-25.xlsx

In [19]:
filename = next(iter(uploaded))

In [3]:
# INCI name produtos
from google.colab import files
inci = files.upload()

Saving inci_16_08.xlsx to inci_16_08.xlsx

In [4]:
filename2 = next(iter(inci))

# Bibliotecas Phyton

In [20]:
#Carrega Bibliotecas
import pandas as pd
import numpy as np
import re

In [21]:
pip install unidecode

Requirement already satisfied: unidecode in /usr/local/lib/python3.12/dist-packages (1.4.0)

In [22]:
from unidecode import unidecode

#Carrega Bases de Dados 1) Lançamento; 2) INCI

## Upload Lançamentos

In [23]:
#Carrega o banco de dados como tabela
data = '/content/'+filename
df_launches = pd.read_excel(data)
pd.options.display.max_columns = None
df_launches.nunique()

Número do Produto                   6220
Data de Publicação                   430
Produto                             3741
Marca                               3495
Empresa                              908
Categoria                              4
Sub-Categoria                         39
Descrição do Produto                6219
Preço por 100g/ml                   3218
Preço em moeda local                1333
Tipo de Lançamento                     5
Posicionamento                      4622
Ingredients (Standard form)         6032
Fabricante                           812
Território da empresa fabricante      25
Local de fabricação                   34
Manufacturer Company Address         529
Link da Imagem Primária             6220
dtype: int64

##Upload INCI

In [24]:
data = '/content/'+filename2
df_inci = pd.read_excel(data)
pd.options.display.max_columns=None
df_inci.nunique()

Produto        51
Ingrediente    50
Prioridade      3
dtype: int64

#Formulas

## Procura INCI

In [25]:
#this checks if any combination of INCI as present in Ingredient
def verifica_ingrediente(formula,produto,material):
  quantidade = len(produto.difference(formula))
  if quantidade == 0:
    return material
  return None

In [26]:
#If last code is true, this returns the material name
def procura_produtos(formula, produtos, materiais):
  formula = formula.copy()
  resultados = []
  for prod, mat in zip(produtos, materiais):
    resultado = verifica_ingrediente(formula, prod, mat)
    if resultado is not None:
      formula = formula.difference(prod) ## Para remover os ingredientes já encontrados numa nova busca.
      resultados.append(resultado)
  return resultados

##Função de Iteração + Soma

In [27]:
def to_set(x):
  try:
    if isinstance(x, pd.DataFrame):
        return x.apply(to_set)
    else:
        return set(x.sum())
  except:
        pass

## Transpoe coluna Categoria

In [28]:
def transpor_2 (df, coluna, linha):
  for cat in df[coluna].unique():
    f = df[coluna] == cat
    df[cat] = df[f][linha]
    f = df[cat].isna()
    df.loc[f, cat] = df.loc[f, cat].apply(lambda x:x)

# Dicionários

In [29]:
#Usado para Fabricantes / Distribuidor, remove as palavras do dicionário abaixo (criar indice para fabricante)
def formatar_fabricantes(coluna):
  remover = [
             'de castro', 'do brasil', 'brasil',
             'fabrica', 'fabricacao', 'manuf', 'tercerizacao', 'manufacturing',
             'farmacia', 'farmacias', 'farmaceuticos', 'drogaria','drogarias', 'farm',
             'cosmetico', 'cometico','cosmeticos', 'cometicos', 'cosmetics', 'cosmetic',
             'cosmiatria', 'cosmetica', 'cosmeticas', 'cosm', 'cosme', 'kosmetics', 'cosmet', 'cosmesticos',
             'ltda','epp', 'eireli', 'me', 'eirell', 'sa', 'eir', 'ltd', 's a',
             'indústria','industria', 'industrias', 'industrial', 'indutrial', 'ind', 'industriae',
             'comercio', 'comecio', 'comercial', 'corporation', 'com', 'de ae',
             'imp', 'exp',  'prod', 'exportacao','importacao','importadora', 'import',
             'do', 'e', 'para', 'de', 'le', 'la',
             'aerossois', 'aerosol', 'aerossol', 'tecnologia', 'profissional',
             'laboratorio','laboratorios', 'laboratories', 'laboratoire', 'instituto', 'group',
             'pesquisa', 'desenvolvimento', 'naturais', 'professional', 'aromatizantes',
             'produtos', 'Produto', 'saneantes', 'quimica', 'quimicos', 'quimico', 'farmaceutica', 'veterinário',
             'higiene','pessoal', 'limpeza', 'botanico', 'beauty',
             'perfumes','fragrancias', 'perfumaria', 'medicamentos', 'perf',
             'distribuidora', 'dist', 'amostras', 'faturamento',
             'international', 'internacional', 'sulamericana', 'nacional',
             'nbsp;', 'veer','serv', 'vajerista', 'amaral', 'jbs', 'nova',  'bioage',
           ]
  pat = '\\b({})\\b'.format('|'.join(remover))
  coluna = (
    coluna
    .apply(unidecode)
    .str.lower()
    .replace("\(.*?\)",'',regex=True)
    .replace('\.', '',regex=True)
    .replace('\/', '',regex=True)
    .replace('\-', '',regex=True)
    .replace(pat,'',regex=True)
    .replace(',', '',regex=True)
    .replace('\s+','',regex=True) #Tirar numeros
    .str.strip()
  )
  return coluna

<>:29: SyntaxWarning: invalid escape sequence '\('
<>:30: SyntaxWarning: invalid escape sequence '\.'
<>:31: SyntaxWarning: invalid escape sequence '\/'
<>:32: SyntaxWarning: invalid escape sequence '\-'
<>:35: SyntaxWarning: invalid escape sequence '\s'
<>:29: SyntaxWarning: invalid escape sequence '\('
<>:30: SyntaxWarning: invalid escape sequence '\.'
<>:31: SyntaxWarning: invalid escape sequence '\/'
<>:32: SyntaxWarning: invalid escape sequence '\-'
<>:35: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-515921065.py:29: SyntaxWarning: invalid escape sequence '\('
  .replace("\(.*?\)",'',regex=True)
/tmp/ipython-input-515921065.py:30: SyntaxWarning: invalid escape sequence '\.'
  .replace('\.', '',regex=True)
/tmp/ipython-input-515921065.py:31: SyntaxWarning: invalid escape sequence '\/'
  .replace('\/', '',regex=True)
/tmp/ipython-input-515921065.py:32: SyntaxWarning: invalid escape sequence '\-'
  .replace('\-', '',regex=True)
/tmp/ipython-input-515921065.py:35: SyntaxWarning: invalid escape sequence '\s'
  .replace('\s+','',regex=True) #Tirar numeros

In [30]:
#Dis dict clean the name of material
def formatar_material(coluna):
  remover = ['BELSIL®', 'BELSIL', 'BELSIM',
             'DRUM', 'ST', 'PE', 'CANISTER', 'RD', 'CARTON', 'IBC PE', '2', 'WOPAL',
             'SBPAL', 'STPAL', 'HOBBOCK', 'SACK', 'BOTTLE',
             '0,45KG','10KG','15KG','25KG', '30G', '50G', '60G', '100KG', '140KG', '150KG', '160KG',
             '180KG', '190KG', '200KG', '210KG', '900KG', '950KG', '190', '20KG',
             'KG', 'AMOSTRA', 'PA', 'XY', 'CP', 'SILICONE ELASTOMER GEL',
             'BR', 'DE', ' E', 'BLOCKED',
             'EMB. 0,100 KG', 'Ver  Pf 100', 'USP',
           ]
  pat = '\\b({})\\b'.format('|'.join(remover))
  coluna = (
    coluna
    .replace(pat,'',regex=True)
    .replace('\#','', regex=True)
    .replace('\"','', regex=True)
    .str.replace('\/', '',regex=True)
    .str.replace('\-', '',regex=True)
    .str.replace('\*', '',regex=True)
    .str.title()
    .str.strip()
  )
  return coluna

<>:16: SyntaxWarning: invalid escape sequence '\#'
<>:18: SyntaxWarning: invalid escape sequence '\/'
<>:19: SyntaxWarning: invalid escape sequence '\-'
<>:20: SyntaxWarning: invalid escape sequence '\*'
<>:16: SyntaxWarning: invalid escape sequence '\#'
<>:18: SyntaxWarning: invalid escape sequence '\/'
<>:19: SyntaxWarning: invalid escape sequence '\-'
<>:20: SyntaxWarning: invalid escape sequence '\*'
/tmp/ipython-input-2499157392.py:16: SyntaxWarning: invalid escape sequence '\#'
  .replace('\#','', regex=True)
/tmp/ipython-input-2499157392.py:18: SyntaxWarning: invalid escape sequence '\/'
  .str.replace('\/', '',regex=True)
/tmp/ipython-input-2499157392.py:19: SyntaxWarning: invalid escape sequence '\-'
  .str.replace('\-', '',regex=True)
/tmp/ipython-input-2499157392.py:20: SyntaxWarning: invalid escape sequence '\*'
  .str.replace('\*', '',regex=True)

In [31]:
#Atribui estado com base no endereço do fabricante / Manufacturer
dict = {'AC':'AC', 'AL':'AL', 'AM':'AM', 'AP':'AP', 'BA':'BA', 'CE':'CE', 'DF':'DF', 'ES':'ES', 'GO':'GO', 'MA':'MA',
     'MG':'MG', 'MS':'MS', 'MT':'MT', 'PA':'PA', 'PB':'PB', 'PE':'PE', 'PI':'PI', 'PR':'PR', 'RJ':'RJ', 'RN':'RN',
     'RO':'RO', 'RR':'RR', 'RS':'RS', 'SC':'SC', 'SE':'SE', 'SP':'SP', 'TO':'TO', 'Sao Paulo':'SP', 'São Paulo':'SP',
     'Sao Paolo':'SP','Osasco': 'SP', 'Mogi das Cruzes': 'SP', 'Cotia':'SP', 'Diadema':'SP', 'São Roque':'SP',
     'São Sebastião':'SP', 'Lins':'SP', 'Cajamar':'SP', 'Pirassununga':'SP', 'Paulista': 'SP', 'São Paolo':'SP',
     'Elisario':'SP', 'Valinhos':'SP', 'Piracaia':'SP', 'São José do Rio Preto':'SP', 'Sao José do Rio Preto':'SP',
     'São José dos Campos':'SP',      'Araras':'SP', 'São Bernardo do Campo':'SP', 'São José dos Campos':'SP',
     'Sao Caetano do Sul':'SP', 'São José do Rio Preto':'SP', 'Brodowski':'SP', 'Cajuru':'SP', 'Itaquaquecetuba':'SP',
     'Itupeva':'SP', 'SO':'SP', 'Mairiporã':'SP', 'Itaquera':'SP', 'Franco da Rocha':'SP', 'Guarulhos':'SP',
     'Bairro Jardim America':'SP', 'Jardim Brazil':'SP', 'Agudos':'SP', 'Itapira':'SP', 'Rib. Preto':'SP', 'Vinhedo':'SP',
     'Lorena':'SP', 'Caieiras': 'SP', 'Louveira':'SP', 'Taboao da Serra':'SP', 'Hortôlandia':'SP', 'Americana':'SP',
     'Macatuba':'SP', 'Boituva':'SP', 'Jandira':'SP', 'Bom Jesus':'SP', 'Atibaia':'SP',
     'Ribeirão Preto':'SP', 'Cabreúva': 'SP', 'Presidente Prudente':'SP', 'Jurubatuba':'SP',
     'Jaú':'SP',
     'Rio de Janeiro':'RJ', 'Rio De Janeiro':'RJ', 'Nova Iguaçu': 'RJ', 'Nova Iguacu': 'RJ', 'Nivopolis':'RJ',
     'Duque de Caixas':'RJ', 'Engenheiro Pedreira':'RJ', 'Areal':'RJ', 'Duque de Caxias':'RJ',
     'Vila Velha':'ES', 'Marechal Floriano':'ES', 'Cariacica':'ES', 'Bom Pastor':'ES',
     'Belo Horizonte':'MG', 'Minas Gerais':'MG', 'Pocos de Caldas':'MG', 'Viçosa':'MG', 'Vicosa':'MG',
     'Pouso Alegre': 'MG', 'Uberlândia':'MG', 'Uberlandia':'MG', 'Ipatinga':'MG', 'Mirabela':'MG','Nova Lima':'MG',
     'São José da Lapa':'MG', 'Sao José da Lapa':'MG', 'Sao Jose da Lapa':'MG', 'Divinópolis':'MG',
     'Tres Pontas':'MG', 'Castelo BH':'MG', 'Varginha':'MG', 'Elói Mendes':'MG', 'Sete Lagoas':'MG',
     'Lagoa Santa':'MG',
     'Porto Alegre':'RS', 'Estância Velha': 'RS', 'Caxias do Sul':'RS', 'Passo Fundo':'RS', 'Gravatai':'RS',
     'Panambi':'RS', 'Gramado':'RS', 'Roca Sales':'RS',
     'Santa Catarina':'SC', 'Joinville':'SC','Camboriu':'SC', 'Maluche':'SC', 'Araquari':'SC', 'Criciúma': 'SC',
     'Criciuma': 'SC', 'Chapecó':'SC', 'Três Barras': 'SC', 'Palhoça':'SC', 'Palhoca':'SC',
     'Colombo':'PR', 'Paraná':'PR', 'Curitiba':'PR', 'Sao José dos Pinhais':'PR','BR 116 Km 85':'PR',
     'Cambé':'PR', 'Fazenda Rio Grande':'PR', 'Mandaguaçu':'PR', 'Pinhais':'PR',
     'Goiana':'GO', 'Goiânia':'GO', 'Anápolis':'GO', 'Anapolis':'GO', 'Go':'GO', 'Itapuranga': 'GO',
     'Guapó':'GO', 'Itajaí':'GO',
     'Brasília': 'DF', 'Brasilia': 'DF',
     'Rondônia':'RO','Novo Hamburgo':'RO','Manaus':'AM', 'Pará':'PA',
     'Bahia':'BA', 'Lauro de Freites': 'BA', 'Lauro de Freitas': 'BA', 'Av. Queira Deus':'BA',
     'Vila Cia Sul':'BA', 'Juazeiro':'BA',
     'Recife':'PE', 'Camaragibe': 'PE', 'Abreu e Lima':'PE', 'Fortaleza':'CE', 'Ceará':'CE', 'Caucaia':'CE',
     'Aracaju': 'SE', 'Nossa Sra. do Socorro':'SE',
     }

#Cria tabelas adicionais

In [34]:
df_launches['mmaaaa']=df_launches['Data de Publicação']

## Cria coluna de Estado, baseado no endereço do Manufacturer

In [35]:
df_launches['State'] = df_launches['Manufacturer Company Address'].str.extract('('+'|'.join(dict)+')',expand=False).map(dict)
#Exibe a quantidade de casos únicos

## Analisa se Ingrediente contém Silicone

In [36]:
#Dicionário Silicones geral
dictOTHERS = {'methicone':'1', 'Dimethicone':'1','methicone Crosspolymer':'1','methiconol':'1',
              'ylsiloxysilicate':'1', 'ylsilsesquioxane':'1', 'Disiloxane':'1', 'Silica':'1','siloxane':'1'}

In [37]:
df_launches['Silicone'] = df_launches['Ingredients (Standard form)'].str.extract('('+'|'.join(dictOTHERS)+')',expand=False).map(dictOTHERS)

## Busca Produtos com INCI listado

In [40]:
df_inci.dropna(inplace=True)
df_inci['Produto'] = formatar_material(df_inci['Produto'])

In [41]:
#Cria uma lista iterável dos ingredientes nos Produtos
df_inci['Ing'] = formatar_material(df_inci['Ingrediente']).str.split(', ').apply(set)

In [42]:
#Conta a quantidade de ingredientes
df_inci.sort_values('Prioridade', ascending=True, inplace=True)

In [43]:
 #Dicionário de palavras a remover da coluna Ingredientes no Mintel
 dictIng={' Andor ':',',
          ', ':',',
          ' ,':',',
          ' (And) ':',',
          }

In [44]:
#Cria uma lista iterável das formulas do mintel
df_launches['Ingredients (Standard form)'] = df_launches['Ingredients (Standard form)'].astype(str)
df_launches['Ing'] = formatar_material(df_launches['Ingredients (Standard form)']).replace(dictIng,regex=True).dropna().str.split(',').apply(set)

In [45]:
#Aplica a função Procura Produtos
df_launches[''] = df_launches['Ing'].apply(lambda formulacao:procura_produtos(formulacao, df_inci['Ing'], df_inci['Produto']))

## Remover Clientes Diretos

In [53]:
dictClientes = {'Devintex Cosméticos':'1', 'Devintex':'1','Procosa Produtos de Beleza':'1', 'Colgate-Palmolive':'1', 'Unilever':'1',
                'Savoy Indústria de Cosméticos':'1', 'Beiersdorf':'1', 'Johnson & Johnson':'1',
                'Procter & Gamble':'1','Química Amparo':'1', "Oréal":'1', 'Procosa':'1',
                'Unilever Brasil Industrial':'1', 'Botica Comercial Farmacêutica':'1'}
dictMarcas = { 'Boticário':'1', 'Siàge':'1', 'Natura ':'1', 'Avon ':'1', 'Eudora':'1',
              'Wella':'1', 'The Body Shop':'1', 'Quem Disse,':'1', 'Salon Line':'1', 'Maybelline':'1'}
df_launches['Clientes']= df_launches['Fabricante'].str.extract('('+'|'.join(dictClientes)+')',expand=False).map(dictClientes)
df_launches['Clientes2'] = df_launches['Marca'].str.extract('('+'|'.join(dictMarcas)+')',expand=False).map(dictMarcas)
df_ = df_launches[df_launches['Clientes']=='1']
df_ = df_[df_['Clientes2']=='1']
df_.to_excel("LancClientes.xlsx")

In [54]:
#Remove clientes  da base de tratamento
df_launches = df_launches[df_launches['Clientes']!='1']
df_launches = df_launches[df_launches['Clientes2']!='1']

## Relatório Linha a Linha

In [70]:
#Cria a coluna que irá indexar a mistura com a planilha do mintel
df_launches['Fabricante']=df_launches['Fabricante'].astype(str)
df_launches['KeyManuf'] = formatar_fabricantes(df_launches['Fabricante'])

In [73]:
col=['Data de Publicação','Sub-Categoria', 'Produto', 'Marca', 'Empresa', 'Fabricante', 'KeyManuf', 'State',
     'Silicone', '', 'Ing', 'Manufacturer Company Address','Preço por 100g/ml']

In [74]:
df_launches[col].to_excel("Lancamentos Linha a Linha.xlsx")

## Gera Relatório de Lançamentos com Categorias Transposta

In [75]:
df_launches['indice'] = 1

In [76]:
transpor_2(df_launches, 'Categoria', 'indice')

KeyError: 'Category'

In [ ]:
#renomeia coluna categoria
df_launches.rename(columns={'Skincare':'Skin', 'Hair Products':'Hair',
                          'Soap & Bath Products':'Bath', 'Colour Cosmetics': 'Make',
                            'Record ID':'Total Lançamentos'},inplace=True)

In [ ]:
df_c = df_launches.groupby(['Market','KeyManuf', 'State'])[['Skin', 'Hair', 'Make', 'Bath']].apply(lambda x:x.count())

In [ ]:
#cria tabela que lista o fabricante, o estado e o total de lançamentos, quais tem silicone,
#e quais tem o claim sem silicone.
df_b = df_launches.groupby(['Market','KeyManuf', 'State']).agg({
                                            'Total Lançamentos': 'count',
                                             'Silicone':'count',
                                             'Free from':'count',
                                              '':to_set})

In [ ]:
#Une tabelas anteriores
df_launches_fab = pd.concat([df_c, df_b], axis=1).reset_index()

# Generate a Report will all information

In [ ]:
df_launches_fab.to_excel('Final Brasil.xlsx')